config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resource :accounts, only: %i(show)
  resources :transfers, only: %i(create)
end

app/models/account.rb
class Account
  DEFAULT_HOST = 'bigalice2.nem.ninja'.freeze
  require 'pp'
  require 'nem'
  attr_reader :node

  def initialize
    @node = Nem::Node.new(host: DEFAULT_HOST)
  end

  def get_info(address)
    account_endpoint = Nem::Endpoint::Account.new(@node)
    account_endpoint.find(address)
  end

  def transfer(params)
    private_key = params[:private_key]
    keypair = Nem::Keypair.new(private_key)
    tx_endpoint = Nem::Endpoint::Transaction.new(@node)
    tx = Nem::Transaction::Transfer.new(params[:recipient], params[:amount].to_f, '送金テストです')
    request = Nem::Request::Announce.new(tx, keypair)
    tx_endpoint.announce(request)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def show
    account = Account.new
    @account_info = account.get_info(account_params[:address])
  end

  private

  def account_params
    params.require(:account).permit(:address)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  def create
    account = Account.new
    @response = account.transfer(transfer_params)
  end

  private

  def transfer_params
    params.require(:transfer).permit(:private_key, :recipient, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/show.html.haml
%h2 アカウント情報
%p アドレス：#{@account_info.address}
%p 残高： #{@account_info.balance.to_f / 1000000}XEM

%h2 送金
.row
  .col-md-6
    = simple_form_for(:transfer, url: transfers_path, remote: true) do |f|
      = f.error_notification
      .form-group
        = f.input :recipient, required: false
        = f.input :private_key, required: false
        = f.input :amount, required: false, input_html: { class: 'fit-input' }
      .form-action
        = f.button :submit, 'XEMを送金する', class: 'btn btn-primary btn', data: { disable_with: '送信中...' }

%h2 送金結果
.js-transfer-result

app/views/home/index.html.haml
%h2 アカウント情報の取得
.row
  .col-md-6
    = simple_form_for(:account, url: accounts_path, method: :get) do |f|
      = f.error_notification
      .form-group
        = f.input :address, required: false, placeholder: 'ここにNEMアドレスを入力して下さい。'
      .form-action
        = f.button :submit, 'アカウント情報を取得する', class: 'btn btn-primary btn', data: { disable_with: '送信中...' }

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      .navbar-brand Nem Ruby Transfer Sample

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title NemRubyTransferSample
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      = render 'layouts/navigation'
    %main{ role: 'main' }
      %section
        .container
          = yield

app/views/transfers/create.js.erb
$('.js-transfer-result').html('<div class="alert alert-warning"><%= @response.message %></div>');